export const categories = [
  { id: "1", name: "Motors" },
  { id: "2", name: "Real Estate" },
  { id: "3", name: "Jobs" },
  { id: "4", name: "Services" },
  { id: "5", name: "Phones & Tablets" },
  { id: "6", name: "Computers" },
  { id: "7", name: "TV, Audio & Photo" },
  { id: "8", name: "Games & Consoles" },
  { id: "9", name: "Home & Garden" },
  { id: "10", name: "Sports & Hobbies" },
  { id: "11", name: "Music & Movies" },
  { id: "12", name: "Animals" },
  { id: "13", name: "Fashion" },
  { id: "14", name: "Baby & Kids" },
  { id: "15", name: "Other" },
]

export const regions = [
  { id: "1", name: "Piemonte" },
  { id: "2", name: "Valle d'Aosta" },
  { id: "3", name: "Lombardia" },
  { id: "4", name: "Liguria" },
  { id: "5", name: "Trentino-Alto Adige" },
  { id: "6", name: "Veneto" },
  { id: "7", name: "Friuli-Venezia Giulia" },
  { id: "8", name: "Emilia-Romagna" },
  { id: "9", name: "Toscana" },
  { id: "10", name: "Umbria" },
  { id: "11", name: "Marche" },
  { id: "12", name: "Lazio" },
  { id: "13", name: "Abruzzo" },
  { id: "14", name: "Molise" },
  { id: "15", name: "Campania" },
  { id: "16", name: "Puglia" },
  { id: "17", name: "Basilicata" },
  { id: "18", name: "Calabria" },
  { id: "19", name: "Sicilia" },
  { id: "20", name: "Sardegna" },
]
